/**
 * PythonAllocateBridge.js
 * GAS → Python割当エンジン連携
 *
 * Public functions:
 *   - runPythonAllocate(weekStartStr) - メイン実行関数
 */

/**
 * Python割当エンジンでスケジュールを生成する。
 * 既存のGAS割当ロジックとは独立して動作。
 * @param {string} weekStartStr - 週開始日 "yyyy/MM/dd"
 * @returns {Object} {success, message, assigned, unassigned}
 */
function runPythonAllocate(weekStartStr) {
  try {
    var ss = SpreadsheetApp.openById(SPREADSHEET_ID);
    var tz = ss.getSpreadsheetTimeZone();

    if (!weekStartStr) {
      throw new Error('週開始日を指定してください');
    }

    // ============================================================
    // 1. Collect data from sheets
    // ============================================================

    // 1a. Staff masters
    var staffMasters = pyb_loadStaffMasters_(ss, tz);

    // 1b. Patient masters
    var patientMasters = pyb_loadPatientMasters_(ss, tz);

    // 1c. Weekly requests (already generated by GAS)
    var weeklyRequests = pyb_loadWeeklyRequests_(ss, tz, weekStartStr);

    // 1d. Events
    var events = pyb_loadEvents_(ss, tz, weekStartStr);

    // 1e. Staff changes
    var staffChanges = pyb_loadStaffChanges_(ss, tz, weekStartStr);

    // 1f. Weekly patterns (from new pattern editor)
    var weeklyPatterns = pyb_loadWeeklyPatterns_(ss, tz);

    // 1g. Confirmed history (for rotation)
    var confirmedHistory = pyb_loadConfirmedHistory_(ss, tz, weekStartStr);

    // ============================================================
    // 2. Send to Python API
    // ============================================================
    var payload = {
      week_start: weekStartStr,
      staff_masters: staffMasters,
      patient_masters: patientMasters,
      weekly_requests: weeklyRequests,
      events: events,
      staff_changes: staffChanges,
      weekly_patterns: weeklyPatterns,
      confirmed_history: confirmedHistory
    };

    var url = API_BASE_URL + '/api/allocate';
    var options = {
      method: 'post',
      contentType: 'application/json',
      payload: JSON.stringify(payload),
      muteHttpExceptions: true
    };

    console.log('Python割当エンジン呼び出し: ' + weeklyRequests.length + '件のリクエスト');
    var response = UrlFetchApp.fetch(url, options);
    var statusCode = response.getResponseCode();
    var result = JSON.parse(response.getContentText());

    if (statusCode !== 200 || !result.success) {
      return {
        success: false,
        message: 'Python割当エラー: ' + (result.error || result.message || 'HTTP ' + statusCode)
      };
    }

    // ============================================================
    // 3. Write results to 割当結果 sheet
    // ============================================================
    var assignmentResults = result.result.assignment_results || [];
    var summary = result.result.summary || {};

    pyb_writeAssignmentResults_(ss, tz, assignmentResults);

    // Also write unassigned report
    var unassigned = result.result.unassigned || [];
    pyb_writeUnassigned_(ss, tz, unassigned);

    return {
      success: true,
      message: summary.message || ('割当完了: ' + assignmentResults.length + '件'),
      assigned: summary.assigned || 0,
      unassigned: summary.unassigned || 0
    };

  } catch (e) {
    console.error('runPythonAllocate error: ' + e.message);
    return { success: false, message: 'エラー: ' + e.message };
  }
}

// ============================================================
// Data Loading Functions (Private)
// ============================================================

function pyb_loadStaffMasters_(ss, tz) {
  var sheet = ss.getSheetByName('スタッフマスタ');
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length < 2) return [];
  var h = data[0];

  function fc(name) {
    for (var i = 0; i < h.length; i++) {
      if (String(h[i]).indexOf(name) >= 0) return i;
    }
    return -1;
  }

  var ci = {
    id: fc('staff_id'), name: fc('スタッフ名'), gender: fc('性別'),
    lat: fc('緯度'), lng: fc('経度'),
    shiftS: fc('シフト開始'), shiftE: fc('シフト終了'),
    days: fc('勤務曜日'), areas: fc('得意エリア'),
    maxPer: fc('最大訪問件数'), alloc: fc('割当量')
  };

  var results = [];
  for (var i = 1; i < data.length; i++) {
    var r = data[i];
    var sid = ci.id >= 0 ? String(r[ci.id] || '') : '';
    if (!sid) continue;
    results.push({
      staff_id: sid,
      staff_name: ci.name >= 0 ? String(r[ci.name] || '') : '',
      gender: ci.gender >= 0 ? String(r[ci.gender] || '') : '',
      latitude: ci.lat >= 0 ? (r[ci.lat] || null) : null,
      longitude: ci.lng >= 0 ? (r[ci.lng] || null) : null,
      shift_start_minutes: ci.shiftS >= 0 ? pyb_timeToMin_(r[ci.shiftS], tz) || 540 : 540,
      shift_end_minutes: ci.shiftE >= 0 ? pyb_timeToMin_(r[ci.shiftE], tz) || 1080 : 1080,
      work_days: ci.days >= 0 ? pyb_parseDayList_(r[ci.days]) : [],
      areas: ci.areas >= 0 ? pyb_parseList_(r[ci.areas]) : [],
      max_per_day: ci.maxPer >= 0 ? (Number(r[ci.maxPer]) || 999) : 999,
      alloc_pref: ci.alloc >= 0 ? String(r[ci.alloc] || '均等') : '均等'
    });
  }
  return results;
}

function pyb_loadPatientMasters_(ss, tz) {
  var sheet = ss.getSheetByName('患者マスタ');
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length < 2) return [];
  var h = data[0];

  function fc(name) {
    for (var i = 0; i < h.length; i++) {
      if (String(h[i]).replace(/[\s\u3000]/g, '').indexOf(name.replace(/[\s\u3000]/g, '')) >= 0) return i;
    }
    return -1;
  }

  var ci = {
    pid: fc('patient_id'), name: fc('患者名'), area: fc('エリア'),
    lat: fc('緯度'), lng: fc('経度'), svc: fc('サービス時間')
  };

  var results = [];
  for (var i = 1; i < data.length; i++) {
    var r = data[i];
    var pid = ci.pid >= 0 ? String(r[ci.pid] || '') : '';
    if (!pid) continue;
    results.push({
      patient_id: pid,
      patient_name: ci.name >= 0 ? String(r[ci.name] || '') : '',
      area: ci.area >= 0 ? String(r[ci.area] || '') : '',
      latitude: ci.lat >= 0 ? (r[ci.lat] || null) : null,
      longitude: ci.lng >= 0 ? (r[ci.lng] || null) : null,
      service_minutes: ci.svc >= 0 ? (Number(r[ci.svc]) || 60) : 60
    });
  }
  return results;
}

function pyb_loadWeeklyRequests_(ss, tz, weekStartStr) {
  var sheet = ss.getSheetByName('週間リクエスト');
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length < 2) return [];
  var h = data[0];

  function fc(name) {
    for (var i = 0; i < h.length; i++) {
      if (String(h[i]).replace(/[\s\u3000]/g, '').indexOf(name.replace(/[\s\u3000]/g, '')) >= 0) return i;
    }
    return -1;
  }

  var ci = {
    date: fc('日付'), youbi: fc('曜日'), pid: fc('patient_id'), pname: fc('患者名'),
    area: fc('エリア'), start: fc('開始時刻'), end: fc('終了時刻'),
    svc: fc('サービス時間'), need: fc('必要スタッフ数'),
    specIds: fc('指定スタッフID'), specType: fc('指定タイプ'),
    ngIds: fc('NGスタッフID'), sex: fc('性別制限'), cont: fc('継続希望'),
    change: fc('変更区分'), prevSid: fc('前回担当スタッフID'),
    prevSname: fc('前回担当スタッフ名'),
    timeType: fc('時間タイプ'), earliest: fc('希望最早'), latest: fc('希望最遅'),
    note: fc('備考')
  };

  // Calculate week date range for filtering
  var wsParts = weekStartStr.split('/');
  var wsDate = new Date(parseInt(wsParts[0]), parseInt(wsParts[1]) - 1, parseInt(wsParts[2]));
  var weekDates = {};
  for (var d = 0; d < 7; d++) {
    var dd = new Date(wsDate.getTime() + d * 86400000);
    weekDates[Utilities.formatDate(dd, tz, 'yyyy/MM/dd')] = true;
  }

  var results = [];
  for (var i = 1; i < data.length; i++) {
    var r = data[i];
    var dateVal = ci.date >= 0 ? r[ci.date] : null;
    if (!dateVal) continue;
    var dateStr = (dateVal instanceof Date) ? Utilities.formatDate(dateVal, tz, 'yyyy/MM/dd') : String(dateVal);

    // Filter to this week only
    if (!weekDates[dateStr]) continue;

    var changeType = ci.change >= 0 ? String(r[ci.change] || '通常') : '通常';
    if (changeType === 'キャンセル') continue;

    results.push({
      request_id: 'R' + i,
      date: dateStr,
      weekday: ci.youbi >= 0 ? pyb_normalizeWeekday_(r[ci.youbi]) : '',
      patient_id: ci.pid >= 0 ? String(r[ci.pid] || '') : '',
      patient_name: ci.pname >= 0 ? String(r[ci.pname] || '') : '',
      area: ci.area >= 0 ? String(r[ci.area] || '') : '',
      start_time_minutes: ci.start >= 0 ? pyb_timeToMin_(r[ci.start], tz) : null,
      end_time_minutes: ci.end >= 0 ? pyb_timeToMin_(r[ci.end], tz) : null,
      service_minutes: ci.svc >= 0 ? (Number(r[ci.svc]) || 60) : 60,
      need_staff: ci.need >= 0 ? (Number(r[ci.need]) || 1) : 1,
      specified_staff_ids: ci.specIds >= 0 ? pyb_parseList_(r[ci.specIds]) : [],
      specified_type: ci.specType >= 0 ? String(r[ci.specType] || '') : '',
      ng_staff_ids: ci.ngIds >= 0 ? pyb_parseList_(r[ci.ngIds]) : [],
      sex_limit: ci.sex >= 0 ? String(r[ci.sex] || '') : '',
      continuation_pref: ci.cont >= 0 ? String(r[ci.cont] || '') : '',
      time_type: ci.timeType >= 0 ? String(r[ci.timeType] || '') : '',
      earliest_time_minutes: ci.earliest >= 0 ? pyb_timeToMin_(r[ci.earliest], tz) : null,
      latest_time_minutes: ci.latest >= 0 ? pyb_timeToMin_(r[ci.latest], tz) : null,
      prev_staff_id: ci.prevSid >= 0 ? String(r[ci.prevSid] || '') : '',
      prev_staff_name: ci.prevSname >= 0 ? String(r[ci.prevSname] || '') : '',
      change_type: changeType,
      notes: ci.note >= 0 ? String(r[ci.note] || '') : ''
    });
  }
  return results;
}

function pyb_loadEvents_(ss, tz, weekStartStr) {
  var sheet = ss.getSheetByName('イベントリクエスト');
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length < 2) return [];
  var h = data[0];

  function fc(name) {
    for (var i = 0; i < h.length; i++) {
      if (String(h[i]).indexOf(name) >= 0) return i;
    }
    return -1;
  }

  var ci = {
    evId: fc('event_id'), sid: fc('staff_id'), date: fc('日付'),
    type: fc('イベント種別'), title: fc('タイトル'),
    start: fc('開始時刻'), end: fc('終了時刻'), dur: fc('所要時間'),
    fixed: fc('固定枠')
  };

  // Week date range
  var wsParts = weekStartStr.split('/');
  var wsDate = new Date(parseInt(wsParts[0]), parseInt(wsParts[1]) - 1, parseInt(wsParts[2]));
  var weekDates = {};
  for (var d = 0; d < 7; d++) {
    var dd = new Date(wsDate.getTime() + d * 86400000);
    weekDates[Utilities.formatDate(dd, tz, 'yyyy/MM/dd')] = true;
  }

  var results = [];
  for (var i = 1; i < data.length; i++) {
    var r = data[i];
    var dateVal = ci.date >= 0 ? r[ci.date] : null;
    if (!dateVal) continue;
    var dateStr = (dateVal instanceof Date) ? Utilities.formatDate(dateVal, tz, 'yyyy/MM/dd') : String(dateVal);
    if (!weekDates[dateStr]) continue;

    results.push({
      event_id: ci.evId >= 0 ? String(r[ci.evId] || ('EV' + i)) : ('EV' + i),
      staff_id: ci.sid >= 0 ? String(r[ci.sid] || '') : '',
      date: dateStr,
      event_type: ci.type >= 0 ? String(r[ci.type] || '') : '',
      title: ci.title >= 0 ? String(r[ci.title] || '') : '',
      start_time_minutes: ci.start >= 0 ? pyb_timeToMin_(r[ci.start], tz) : null,
      end_time_minutes: ci.end >= 0 ? pyb_timeToMin_(r[ci.end], tz) : null,
      duration_minutes: ci.dur >= 0 ? (Number(r[ci.dur]) || 60) : 60,
      fixed_slot: ci.fixed >= 0 ? (String(r[ci.fixed]).toUpperCase() === 'TRUE') : true
    });
  }
  return results;
}

function pyb_loadStaffChanges_(ss, tz, weekStartStr) {
  var sheet = ss.getSheetByName('スタッフ個別変更リクエスト');
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length < 2) return [];
  var h = data[0];

  function fc(name) {
    for (var i = 0; i < h.length; i++) {
      if (String(h[i]).indexOf(name) >= 0) return i;
    }
    return -1;
  }

  var ci = { sid: fc('staff_id'), date: fc('日付'), type: fc('制限タイプ'), start: fc('開始時刻'), end: fc('終了時刻') };

  var wsParts = weekStartStr.split('/');
  var wsDate = new Date(parseInt(wsParts[0]), parseInt(wsParts[1]) - 1, parseInt(wsParts[2]));
  var weekDates = {};
  for (var d = 0; d < 7; d++) {
    var dd = new Date(wsDate.getTime() + d * 86400000);
    weekDates[Utilities.formatDate(dd, tz, 'yyyy/MM/dd')] = true;
  }

  var results = [];
  for (var i = 1; i < data.length; i++) {
    var r = data[i];
    var dateVal = ci.date >= 0 ? r[ci.date] : null;
    if (!dateVal) continue;
    var dateStr = (dateVal instanceof Date) ? Utilities.formatDate(dateVal, tz, 'yyyy/MM/dd') : String(dateVal);
    if (!weekDates[dateStr]) continue;

    results.push({
      staff_id: ci.sid >= 0 ? String(r[ci.sid] || '') : '',
      date: dateStr,
      restriction_type: ci.type >= 0 ? String(r[ci.type] || '') : '',
      start_time_minutes: ci.start >= 0 ? pyb_timeToMin_(r[ci.start], tz) : null,
      end_time_minutes: ci.end >= 0 ? pyb_timeToMin_(r[ci.end], tz) : null
    });
  }
  return results;
}

function pyb_loadWeeklyPatterns_(ss, tz) {
  var sheet = ss.getSheetByName('週間訪問パターン');
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length < 2) return [];
  var h = data[0];

  function fc(name) {
    for (var i = 0; i < h.length; i++) {
      if (String(h[i]).indexOf(name) >= 0) return i;
    }
    return -1;
  }

  var ci = { pid: fc('patient_id'), name: fc('患者名'), day: fc('曜日コード'), start: fc('開始時刻'), end: fc('終了時刻'), svc: fc('サービス時間'), need: fc('必要スタッフ数'), note: fc('備考') };

  var results = [];
  for (var i = 1; i < data.length; i++) {
    var r = data[i];
    var pid = ci.pid >= 0 ? String(r[ci.pid] || '') : '';
    if (!pid) continue;
    results.push({
      patient_id: pid,
      patient_name: ci.name >= 0 ? String(r[ci.name] || '') : '',
      day_code: ci.day >= 0 ? String(r[ci.day] || '') : '',
      start_time_minutes: ci.start >= 0 ? pyb_timeToMin_(r[ci.start], tz) : null,
      end_time_minutes: ci.end >= 0 ? pyb_timeToMin_(r[ci.end], tz) : null,
      service_minutes: ci.svc >= 0 ? (Number(r[ci.svc]) || 60) : 60,
      need_staff: ci.need >= 0 ? (Number(r[ci.need]) || 1) : 1,
      note: ci.note >= 0 ? String(r[ci.note] || '') : ''
    });
  }
  return results;
}

function pyb_loadConfirmedHistory_(ss, tz, weekStartStr) {
  var sheet = ss.getSheetByName('確定スケジュール履歴');
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length < 2) return [];
  var h = data[0];

  function fc(name) {
    for (var i = 0; i < h.length; i++) {
      if (String(h[i]).indexOf(name) >= 0) return i;
    }
    return -1;
  }

  var ci = { ws: fc('週開始日'), date: fc('日付'), pid: fc('patient_id'), sid: fc('staff_id'), sname: fc('スタッフ名') };

  // Only load records BEFORE this week
  var results = [];
  for (var i = 1; i < data.length; i++) {
    var r = data[i];
    var ws = ci.ws >= 0 ? String(r[ci.ws] || '') : '';
    if (ws >= weekStartStr) continue; // Only BEFORE this week

    var dateVal = ci.date >= 0 ? r[ci.date] : null;
    var dateStr = dateVal ? ((dateVal instanceof Date) ? Utilities.formatDate(dateVal, tz, 'yyyy/MM/dd') : String(dateVal)) : '';

    results.push({
      week_start: ws,
      date: dateStr,
      patient_id: ci.pid >= 0 ? String(r[ci.pid] || '') : '',
      staff_id: ci.sid >= 0 ? String(r[ci.sid] || '') : '',
      staff_name: ci.sname >= 0 ? String(r[ci.sname] || '') : ''
    });
  }
  return results;
}

// ============================================================
// Write Results Functions (Private)
// ============================================================

function pyb_writeAssignmentResults_(ss, tz, assignments) {
  var sheet = ss.getSheetByName('割当結果');
  if (!sheet) {
    sheet = ss.insertSheet('割当結果');
  }

  // Clear and write header
  sheet.clear();
  var headers = ['visit_id', '日付', '曜日', 'staff_id', 'スタッフ名', 'patient_id', '患者名', 'エリア', '開始時刻', '終了時刻', 'サービス時間', '時間タイプ', '希望最早時刻', '希望最遅時刻', '備考'];
  sheet.getRange(1, 1, 1, headers.length).setValues([headers]);

  if (assignments.length === 0) return;

  var rows = [];
  for (var i = 0; i < assignments.length; i++) {
    var a = assignments[i];
    var dateVal = a.date ? pyb_parseDate_(a.date) : '';
    rows.push([
      a.visit_id || '',
      dateVal || a.date || '',
      a.weekday || '',
      a.staff_id || '',
      a.staff_name || '',
      a.patient_id || '',
      a.patient_name || '',
      a.area || '',
      a.start_time_minutes != null ? a.start_time_minutes / 1440 : '',
      a.end_time_minutes != null ? a.end_time_minutes / 1440 : '',
      a.service_minutes || '',
      a.time_type || '',
      a.earliest_time_minutes != null ? a.earliest_time_minutes / 1440 : '',
      a.latest_time_minutes != null ? a.latest_time_minutes / 1440 : '',
      a.notes || ''
    ]);
  }

  sheet.getRange(2, 1, rows.length, headers.length).setValues(rows);
}

function pyb_writeUnassigned_(ss, tz, unassigned) {
  var sheet = ss.getSheetByName('割当不可');
  if (!sheet) {
    sheet = ss.insertSheet('割当不可');
  }
  sheet.clear();
  var headers = ['日付', '曜日', 'patient_id', '患者名', '必要スタッフ数', '未割当枠', '理由'];
  sheet.getRange(1, 1, 1, headers.length).setValues([headers]);

  if (unassigned.length === 0) return;

  var rows = [];
  for (var i = 0; i < unassigned.length; i++) {
    var u = unassigned[i];
    rows.push([
      u.date_str || u.date || '',
      '',
      u.pid || u.patient_id || '',
      u.pname || u.patient_name || '',
      u.need_staff || 1,
      u.slot || 1,
      u.reason || ''
    ]);
  }
  sheet.getRange(2, 1, rows.length, headers.length).setValues(rows);
}

// ============================================================
// Utility Functions (Private)
// ============================================================

function pyb_timeToMin_(val, tz) {
  if (val === null || val === undefined || val === '') return null;
  if (val instanceof Date) {
    return val.getHours() * 60 + val.getMinutes();
  }
  if (typeof val === 'number') {
    if (val >= 0 && val < 1) return Math.round(val * 24 * 60);
    if (val >= 1 && val < 1440) return Math.round(val);
    return Math.round(val * 24 * 60) % 1440;
  }
  var s = String(val).trim();
  var m = s.match(/(\d{1,2}):(\d{2})/);
  if (m) return parseInt(m[1]) * 60 + parseInt(m[2]);
  return null;
}

function pyb_parseDate_(dateStr) {
  if (!dateStr) return null;
  var parts = String(dateStr).split(/[\/\-]/);
  if (parts.length >= 3) {
    return new Date(parseInt(parts[0]), parseInt(parts[1]) - 1, parseInt(parts[2]));
  }
  return null;
}

function pyb_parseList_(val) {
  if (!val) return [];
  return String(val).split(/[,、\s\/・|]+/).map(function(s) { return s.trim(); }).filter(function(s) { return s; });
}

function pyb_parseDayList_(val) {
  if (!val) return [];
  var items = pyb_parseList_(val);
  var dayMap = {'月':'Mon','火':'Tue','水':'Wed','木':'Thu','金':'Fri','土':'Sat','日':'Sun'};
  return items.map(function(d) { return dayMap[d] || d; });
}

function pyb_normalizeWeekday_(val) {
  if (!val) return '';
  var s = String(val).trim();
  var dayMap = {'月':'Mon','火':'Tue','水':'Wed','木':'Thu','金':'Fri','土':'Sat','日':'Sun',
    'Mon':'Mon','Tue':'Tue','Wed':'Wed','Thu':'Thu','Fri':'Fri','Sat':'Sat','Sun':'Sun'};
  return dayMap[s] || s;
}
