/**
 * PythonAllocateBridge.js
 * GAS → Python割当エンジン連携
 *
 * Public functions:
 *   - runPythonAllocate(weekStartStr) - メイン実行関数
 *   - debugPythonAllocateData(weekStartStr) - データ取得検証
 */

/**
 * Python割当エンジンでスケジュールを生成する。
 * 既存のGAS割当ロジックとは独立して動作。
 * @param {string} weekStartStr - 週開始日 "yyyy/MM/dd"
 * @returns {Object} {success, message, assigned, unassigned}
 */
function runPythonAllocate(weekStartStr) {
  try {
    var ss = SpreadsheetApp.openById(SPREADSHEET_ID);
    var tz = ss.getSpreadsheetTimeZone();

    if (!weekStartStr) {
      throw new Error('週開始日を指定してください');
    }
    // UIセレクタは yyyy-MM-dd 形式、ローダーは yyyy/MM/dd を期待
    weekStartStr = weekStartStr.replace(/-/g, '/');

    // ============================================================
    // 1. Collect data from sheets
    // ============================================================

    // 1a. Staff masters
    var staffMasters = pyb_loadStaffMasters_(ss, tz);

    // 1b. Patient masters
    var patientMasters = pyb_loadPatientMasters_(ss, tz);

    // 1c. Weekly requests (already generated by GAS)
    var weeklyRequests = pyb_loadWeeklyRequests_(ss, tz, weekStartStr);

    // 1d. Events
    var events = pyb_loadEvents_(ss, tz, weekStartStr);

    // 1e. Staff changes
    var staffChanges = pyb_loadStaffChanges_(ss, tz, weekStartStr);

    // 1f. Weekly patterns (from new pattern editor)
    var weeklyPatterns = pyb_loadWeeklyPatterns_(ss, tz);

    // 1g. Confirmed history (for rotation)
    var confirmedHistory = pyb_loadConfirmedHistory_(ss, tz, weekStartStr);

    // 1h. Patient changes (個別変更リクエスト)
    var patientChanges = pyb_loadPatientChanges_(ss, tz, weekStartStr);

    // 1i. Special week (特別訪問週間)
    var specialWeek = pyb_loadSpecialWeek_(ss, tz, weekStartStr);

    // 1j. Mentor pairs (スタッフ同行割付)
    var mentorPairs = pyb_loadMentorPairs_(ss, tz, weekStartStr);

    // ============================================================
    // 2. Send to Python API
    // ============================================================
    var payload = {
      week_start: weekStartStr,
      staff_masters: staffMasters,
      patient_masters: patientMasters,
      weekly_requests: weeklyRequests,
      events: events,
      staff_changes: staffChanges,
      weekly_patterns: weeklyPatterns,
      confirmed_history: confirmedHistory,
      patient_changes: patientChanges,
      special_week: specialWeek,
      mentor_pairs: mentorPairs
    };

    var url = API_BASE_URL + '/api/allocate';
    var options = {
      method: 'post',
      contentType: 'application/json',
      payload: JSON.stringify(payload),
      muteHttpExceptions: true
    };

    console.log('Python割当エンジン呼び出し: ' + weeklyRequests.length + '件のリクエスト');
    var response = UrlFetchApp.fetch(url, options);
    var statusCode = response.getResponseCode();
    var result = JSON.parse(response.getContentText());

    if (statusCode !== 200 || !result.success) {
      return {
        success: false,
        message: 'Python割当エラー: ' + (result.error || result.message || 'HTTP ' + statusCode)
      };
    }

    // ============================================================
    // 3. Write results to 割当結果 sheet
    // ============================================================
    var assignmentResults = result.result.assignment_results || [];
    var summary = result.result.summary || {};

    pyb_writeAssignmentResults_(ss, tz, assignmentResults);

    // Also write unassigned report
    var unassigned = result.result.unassigned || [];
    pyb_writeUnassigned_(ss, tz, unassigned);

    var allocMsg = summary.message || ('割当完了: ' + assignmentResults.length + '件');
    console.log(allocMsg);

    // デバッグ: 未割当詳細と曜日シフト結果
    if (summary.unassigned_detail) {
      console.log('=== 未割当内訳 ===');
      console.log(JSON.stringify(summary.unassigned_detail, null, 2));
    }
    if (summary.day_shifts && summary.day_shifts.length > 0) {
      console.log('=== 曜日シフト成功 ===');
      summary.day_shifts.forEach(function(s) { console.log('  ' + s); });
    } else {
      console.log('=== 曜日シフト成功: なし ===');
    }
    if (summary.day_shift_failures && summary.day_shift_failures.length > 0) {
      console.log('=== 曜日シフト失敗 ===');
      summary.day_shift_failures.forEach(function(s) { console.log('  ' + s); });
    }
    if (summary.coupled_debug) {
      console.log('=== 2名体制不足検出 ===');
      console.log(JSON.stringify(summary.coupled_debug, null, 2));
    }

    // ============================================================
    // 4. 週ビューを更新
    // ============================================================
    console.log('週ビューを更新中...');
    try {
      var weekViewResult = 週ビューを更新_(ss, weekStartStr);
      var weekViewMsg = (weekViewResult && weekViewResult.message) || '週ビュー更新完了';
      console.log(weekViewMsg);
    } catch (e) {
      console.error('週ビュー更新エラー（割当自体は成功）: ' + e.message);
    }

    // ============================================================
    // 5. ルートサマリを作成
    // ============================================================
    console.log('ルートサマリを作成中...');
    try {
      var routeResult = ルートサマリを作成_(ss, weekStartStr);
      var routeMsg = (routeResult && routeResult.message) || 'ルートサマリ作成完了';
      console.log(routeMsg);
    } catch (e) {
      console.error('ルートサマリ作成エラー（割当自体は成功）: ' + e.message);
    }

    return {
      success: true,
      message: allocMsg + ' → 週ビュー・ルートサマリも更新済み',
      assigned: summary.assigned || 0,
      unassigned: summary.unassigned || 0
    };

  } catch (e) {
    console.error('runPythonAllocate error: ' + e.message);
    return { success: false, message: 'エラー: ' + e.message };
  }
}

/**
 * スクリプトエディタから直接実行するテスト関数
 * 実際のスプレッドシートデータでPython割当を実行し、結果をログ出力
 */
function testPythonAllocateFromSheet() {
  var weekStartStr = '2026/03/23'; // ← テストしたい週をここで指定

  console.log('=== Python割当テスト開始 ===');
  console.log('対象週: ' + weekStartStr);

  // Step 1: データ取得検証
  console.log('\n--- Step 1: データ取得検証 ---');
  var debugResult = debugPythonAllocateData(weekStartStr);
  console.log('ローカル件数: ' + JSON.stringify(debugResult.local_counts, null, 2));
  console.log('Python受信件数: ' + JSON.stringify(debugResult.remote_counts, null, 2));
  console.log('ペイロードサイズ: ' + (debugResult.payload_size_bytes / 1024).toFixed(1) + ' KB');

  // Step 2: 実際の割当実行
  console.log('\n--- Step 2: 割当エンジン実行 ---');
  var result = runPythonAllocate(weekStartStr);
  console.log('結果: ' + JSON.stringify(result, null, 2));

  if (result.success) {
    console.log('\n✓ 割当成功! 割当: ' + result.assigned + '件, 未割当: ' + result.unassigned + '件');
  } else {
    console.log('\n✗ 割当失敗: ' + result.message);
  }

  return result;
}

/**
 * デバッグ用: 全データを収集してPython /api/allocate/debug に送信し、
 * 各シートの件数とサンプルデータを返す。
 * GASスクリプトエディタのログで確認可能。
 * @param {string} weekStartStr - 週開始日 "yyyy/MM/dd"
 * @returns {Object} デバッグ結果
 */
function debugPythonAllocateData(weekStartStr) {
  try {
    var ss = SpreadsheetApp.openById(SPREADSHEET_ID);
    var tz = ss.getSpreadsheetTimeZone();

    if (!weekStartStr) {
      throw new Error('週開始日を指定してください（UI側から対象週を選択して実行）');
    }
    // UIセレクタは yyyy-MM-dd 形式、ローダーは yyyy/MM/dd を期待
    weekStartStr = weekStartStr.replace(/-/g, '/');

    var staffMasters = pyb_loadStaffMasters_(ss, tz);
    var patientMasters = pyb_loadPatientMasters_(ss, tz);
    var weeklyRequests = pyb_loadWeeklyRequests_(ss, tz, weekStartStr);
    var events = pyb_loadEvents_(ss, tz, weekStartStr);
    var staffChanges = pyb_loadStaffChanges_(ss, tz, weekStartStr);
    var weeklyPatterns = pyb_loadWeeklyPatterns_(ss, tz);
    var confirmedHistory = pyb_loadConfirmedHistory_(ss, tz, weekStartStr);
    var patientChanges = pyb_loadPatientChanges_(ss, tz, weekStartStr);
    var specialWeek = pyb_loadSpecialWeek_(ss, tz, weekStartStr);
    var mentorPairs = pyb_loadMentorPairs_(ss, tz, weekStartStr);

    // ローカル件数サマリ
    var localCounts = {
      staff_masters: staffMasters.length,
      patient_masters: patientMasters.length,
      weekly_requests: weeklyRequests.length,
      events: events.length,
      staff_changes: staffChanges.length,
      weekly_patterns: weeklyPatterns.length,
      confirmed_history: confirmedHistory.length,
      patient_changes: patientChanges.length,
      special_week_headers: specialWeek.headers.length,
      special_week_details: specialWeek.details.length,
      mentor_pairs: mentorPairs.length
    };

    console.log('=== ローカル件数 ===');
    console.log(JSON.stringify(localCounts, null, 2));

    // Python API に送信して検証
    var payload = {
      week_start: weekStartStr,
      staff_masters: staffMasters,
      patient_masters: patientMasters,
      weekly_requests: weeklyRequests,
      events: events,
      staff_changes: staffChanges,
      weekly_patterns: weeklyPatterns,
      confirmed_history: confirmedHistory,
      patient_changes: patientChanges,
      special_week: specialWeek,
      mentor_pairs: mentorPairs
    };

    var url = API_BASE_URL + '/api/allocate/debug';
    var options = {
      method: 'post',
      contentType: 'application/json',
      payload: JSON.stringify(payload),
      muteHttpExceptions: true
    };

    console.log('Python API /api/allocate/debug 呼び出し...');
    var response = UrlFetchApp.fetch(url, options);
    var statusCode = response.getResponseCode();
    var result = JSON.parse(response.getContentText());

    console.log('HTTP ' + statusCode);
    console.log('=== Python側受信件数 ===');
    console.log(JSON.stringify(result.counts || {}, null, 2));

    if (result.samples) {
      console.log('=== サンプルデータ ===');
      for (var key in result.samples) {
        console.log(key + ': ' + JSON.stringify(result.samples[key]).substring(0, 200));
      }
    }

    return {
      success: true,
      local_counts: localCounts,
      remote_counts: result.counts || {},
      samples: result.samples || {},
      payload_size_bytes: JSON.stringify(payload).length
    };

  } catch (e) {
    console.error('debugPythonAllocateData error: ' + e.message);
    return { success: false, error: e.message };
  }
}

// ============================================================
// Data Loading Functions (Private)
// ============================================================

function pyb_loadStaffMasters_(ss, tz) {
  var sheet = ss.getSheetByName('スタッフマスタ');
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length < 2) return [];
  var h = data[0];

  function fc(name) {
    for (var i = 0; i < h.length; i++) {
      if (String(h[i]).indexOf(name) >= 0) return i;
    }
    return -1;
  }

  var ci = {
    id: fc('staff_id'), name: fc('スタッフ名'), gender: fc('性別'),
    lat: fc('緯度'), lng: fc('経度'),
    shiftS: fc('シフト開始'), shiftE: fc('シフト終了'),
    days: fc('勤務曜日'), areas: fc('得意エリア'),
    maxPer: fc('最大訪問件数'), alloc: fc('割当量')
  };

  var results = [];
  for (var i = 1; i < data.length; i++) {
    var r = data[i];
    var sid = ci.id >= 0 ? String(r[ci.id] || '') : '';
    if (!sid) continue;
    results.push({
      staff_id: sid,
      staff_name: ci.name >= 0 ? String(r[ci.name] || '') : '',
      gender: ci.gender >= 0 ? String(r[ci.gender] || '') : '',
      latitude: ci.lat >= 0 ? (r[ci.lat] || null) : null,
      longitude: ci.lng >= 0 ? (r[ci.lng] || null) : null,
      shift_start_minutes: ci.shiftS >= 0 ? pyb_timeToMin_(r[ci.shiftS], tz) || 540 : 540,
      shift_end_minutes: ci.shiftE >= 0 ? pyb_timeToMin_(r[ci.shiftE], tz) || 1080 : 1080,
      work_days: ci.days >= 0 ? pyb_parseDayList_(r[ci.days]) : [],
      areas: ci.areas >= 0 ? pyb_parseList_(r[ci.areas]) : [],
      max_per_day: ci.maxPer >= 0 ? (Number(r[ci.maxPer]) || 999) : 999,
      alloc_pref: ci.alloc >= 0 ? String(r[ci.alloc] || '均等') : '均等'
    });
  }
  return results;
}

function pyb_loadPatientMasters_(ss, tz) {
  var sheet = ss.getSheetByName('患者マスタ');
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length < 2) return [];
  var h = data[0];

  function fc(name) {
    for (var i = 0; i < h.length; i++) {
      if (String(h[i]).replace(/[\s\u3000]/g, '').indexOf(name.replace(/[\s\u3000]/g, '')) >= 0) return i;
    }
    return -1;
  }

  var ci = {
    pid: fc('patient_id'), name: fc('患者名'), area: fc('エリア'),
    lat: fc('緯度'), lng: fc('経度'), svc: fc('サービス時間'),
    dayPriority: fc('曜日優先度')
  };

  var results = [];
  for (var i = 1; i < data.length; i++) {
    var r = data[i];
    var pid = ci.pid >= 0 ? String(r[ci.pid] || '') : '';
    if (!pid) continue;
    results.push({
      patient_id: pid,
      patient_name: ci.name >= 0 ? String(r[ci.name] || '') : '',
      area: ci.area >= 0 ? String(r[ci.area] || '') : '',
      latitude: ci.lat >= 0 ? (r[ci.lat] || null) : null,
      longitude: ci.lng >= 0 ? (r[ci.lng] || null) : null,
      service_minutes: ci.svc >= 0 ? (Number(r[ci.svc]) || 60) : 60,
      day_priority: ci.dayPriority >= 0 ? String(r[ci.dayPriority] || '低') : '低'
    });
  }
  return results;
}

function pyb_loadWeeklyRequests_(ss, tz, weekStartStr) {
  var sheet = ss.getSheetByName('週間リクエスト');
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length < 2) return [];
  var h = data[0];

  function fc(name) {
    for (var i = 0; i < h.length; i++) {
      if (String(h[i]).replace(/[\s\u3000]/g, '').indexOf(name.replace(/[\s\u3000]/g, '')) >= 0) return i;
    }
    return -1;
  }

  var ci = {
    date: fc('日付'), youbi: fc('曜日'), pid: fc('patient_id'), pname: fc('患者名'),
    area: fc('エリア'), start: fc('開始時刻'), end: fc('終了時刻'),
    svc: fc('サービス時間'), need: fc('必要スタッフ数'),
    specIds: fc('指定スタッフID'), specType: fc('指定タイプ'),
    ngIds: fc('NGスタッフID'), sex: fc('性別制限'), cont: fc('継続希望'),
    change: fc('変更区分'), prevSid: fc('前回担当スタッフID'),
    prevSname: fc('前回担当スタッフ名'),
    timeType: fc('時間タイプ'), earliest: fc('希望最早'), latest: fc('希望最遅'),
    note: fc('備考')
  };

  // Calculate week date range for filtering
  var wsParts = weekStartStr.split('/');
  var wsDate = new Date(parseInt(wsParts[0]), parseInt(wsParts[1]) - 1, parseInt(wsParts[2]));
  var weekDates = {};
  for (var d = 0; d < 7; d++) {
    var dd = new Date(wsDate.getTime() + d * 86400000);
    weekDates[Utilities.formatDate(dd, tz, 'yyyy/MM/dd')] = true;
  }

  var results = [];
  for (var i = 1; i < data.length; i++) {
    var r = data[i];
    var dateVal = ci.date >= 0 ? r[ci.date] : null;
    if (!dateVal) continue;
    var dateStr = (dateVal instanceof Date) ? Utilities.formatDate(dateVal, tz, 'yyyy/MM/dd') : String(dateVal);

    // Filter to this week only
    if (!weekDates[dateStr]) continue;

    var changeType = ci.change >= 0 ? String(r[ci.change] || '通常') : '通常';
    if (changeType === 'キャンセル') continue;

    results.push({
      request_id: 'R' + i,
      date: dateStr,
      weekday: ci.youbi >= 0 ? pyb_normalizeWeekday_(r[ci.youbi]) : '',
      patient_id: ci.pid >= 0 ? String(r[ci.pid] || '') : '',
      patient_name: ci.pname >= 0 ? String(r[ci.pname] || '') : '',
      area: ci.area >= 0 ? String(r[ci.area] || '') : '',
      start_time_minutes: ci.start >= 0 ? pyb_timeToMin_(r[ci.start], tz) : null,
      end_time_minutes: ci.end >= 0 ? pyb_timeToMin_(r[ci.end], tz) : null,
      service_minutes: ci.svc >= 0 ? (Number(r[ci.svc]) || 60) : 60,
      need_staff: ci.need >= 0 ? (Number(r[ci.need]) || 1) : 1,
      specified_staff_ids: ci.specIds >= 0 ? pyb_parseList_(r[ci.specIds]) : [],
      specified_type: ci.specType >= 0 ? String(r[ci.specType] || '') : '',
      ng_staff_ids: ci.ngIds >= 0 ? pyb_parseList_(r[ci.ngIds]) : [],
      sex_limit: ci.sex >= 0 ? String(r[ci.sex] || '') : '',
      continuation_pref: ci.cont >= 0 ? String(r[ci.cont] || '') : '',
      time_type: ci.timeType >= 0 ? String(r[ci.timeType] || '') : '',
      earliest_time_minutes: ci.earliest >= 0 ? pyb_timeToMin_(r[ci.earliest], tz) : null,
      latest_time_minutes: ci.latest >= 0 ? pyb_timeToMin_(r[ci.latest], tz) : null,
      prev_staff_id: ci.prevSid >= 0 ? String(r[ci.prevSid] || '') : '',
      prev_staff_name: ci.prevSname >= 0 ? String(r[ci.prevSname] || '') : '',
      change_type: changeType,
      notes: ci.note >= 0 ? String(r[ci.note] || '') : ''
    });
  }
  return results;
}

function pyb_loadEvents_(ss, tz, weekStartStr) {
  var sheet = ss.getSheetByName('イベントリクエスト');
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length < 2) return [];
  var h = data[0];

  function fc(name) {
    for (var i = 0; i < h.length; i++) {
      if (String(h[i]).indexOf(name) >= 0) return i;
    }
    return -1;
  }

  var ci = {
    evId: fc('event_id'), sid: fc('staff_id'), date: fc('日付'),
    type: fc('イベント種別'), title: fc('タイトル'),
    start: fc('開始時刻'), end: fc('終了時刻'), dur: fc('所要時間'),
    fixed: fc('固定枠')
  };

  // Week date range
  var wsParts = weekStartStr.split('/');
  var wsDate = new Date(parseInt(wsParts[0]), parseInt(wsParts[1]) - 1, parseInt(wsParts[2]));
  var weekDates = {};
  for (var d = 0; d < 7; d++) {
    var dd = new Date(wsDate.getTime() + d * 86400000);
    weekDates[Utilities.formatDate(dd, tz, 'yyyy/MM/dd')] = true;
  }

  var results = [];
  for (var i = 1; i < data.length; i++) {
    var r = data[i];
    var dateVal = ci.date >= 0 ? r[ci.date] : null;
    if (!dateVal) continue;
    var dateStr = (dateVal instanceof Date) ? Utilities.formatDate(dateVal, tz, 'yyyy/MM/dd') : String(dateVal);
    if (!weekDates[dateStr]) continue;

    results.push({
      event_id: ci.evId >= 0 ? String(r[ci.evId] || ('EV' + i)) : ('EV' + i),
      staff_id: ci.sid >= 0 ? String(r[ci.sid] || '') : '',
      date: dateStr,
      event_type: ci.type >= 0 ? String(r[ci.type] || '') : '',
      title: ci.title >= 0 ? String(r[ci.title] || '') : '',
      start_time_minutes: ci.start >= 0 ? pyb_timeToMin_(r[ci.start], tz) : null,
      end_time_minutes: ci.end >= 0 ? pyb_timeToMin_(r[ci.end], tz) : null,
      duration_minutes: ci.dur >= 0 ? (Number(r[ci.dur]) || 60) : 60,
      fixed_slot: ci.fixed >= 0 ? (String(r[ci.fixed]).toUpperCase() === 'TRUE') : true
    });
  }
  return results;
}

function pyb_loadStaffChanges_(ss, tz, weekStartStr) {
  var sheet = ss.getSheetByName('スタッフ個別変更リクエスト');
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length < 2) return [];
  var h = data[0];

  function fc(name) {
    for (var i = 0; i < h.length; i++) {
      if (String(h[i]).indexOf(name) >= 0) return i;
    }
    return -1;
  }

  var ci = { sid: fc('staff_id'), date: fc('日付'), type: fc('制限タイプ'), start: fc('開始時刻'), end: fc('終了時刻') };

  var wsParts = weekStartStr.split('/');
  var wsDate = new Date(parseInt(wsParts[0]), parseInt(wsParts[1]) - 1, parseInt(wsParts[2]));
  var weekDates = {};
  for (var d = 0; d < 7; d++) {
    var dd = new Date(wsDate.getTime() + d * 86400000);
    weekDates[Utilities.formatDate(dd, tz, 'yyyy/MM/dd')] = true;
  }

  var results = [];
  for (var i = 1; i < data.length; i++) {
    var r = data[i];
    var dateVal = ci.date >= 0 ? r[ci.date] : null;
    if (!dateVal) continue;
    var dateStr = (dateVal instanceof Date) ? Utilities.formatDate(dateVal, tz, 'yyyy/MM/dd') : String(dateVal);
    if (!weekDates[dateStr]) continue;

    results.push({
      staff_id: ci.sid >= 0 ? String(r[ci.sid] || '') : '',
      date: dateStr,
      restriction_type: ci.type >= 0 ? String(r[ci.type] || '') : '',
      start_time_minutes: ci.start >= 0 ? pyb_timeToMin_(r[ci.start], tz) : null,
      end_time_minutes: ci.end >= 0 ? pyb_timeToMin_(r[ci.end], tz) : null
    });
  }
  return results;
}

function pyb_loadWeeklyPatterns_(ss, tz) {
  var sheet = ss.getSheetByName('週間訪問パターン');
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length < 2) return [];
  var h = data[0];

  function fc(name) {
    for (var i = 0; i < h.length; i++) {
      if (String(h[i]).indexOf(name) >= 0) return i;
    }
    return -1;
  }

  var ci = { pid: fc('patient_id'), name: fc('患者名'), day: fc('曜日コード'), start: fc('開始時刻'), end: fc('終了時刻'), svc: fc('サービス時間'), need: fc('必要スタッフ数'), note: fc('備考') };

  var results = [];
  for (var i = 1; i < data.length; i++) {
    var r = data[i];
    var pid = ci.pid >= 0 ? String(r[ci.pid] || '') : '';
    if (!pid) continue;
    results.push({
      patient_id: pid,
      patient_name: ci.name >= 0 ? String(r[ci.name] || '') : '',
      day_code: ci.day >= 0 ? String(r[ci.day] || '') : '',
      start_time_minutes: ci.start >= 0 ? pyb_timeToMin_(r[ci.start], tz) : null,
      end_time_minutes: ci.end >= 0 ? pyb_timeToMin_(r[ci.end], tz) : null,
      service_minutes: ci.svc >= 0 ? (Number(r[ci.svc]) || 60) : 60,
      need_staff: ci.need >= 0 ? (Number(r[ci.need]) || 1) : 1,
      note: ci.note >= 0 ? String(r[ci.note] || '') : ''
    });
  }
  return results;
}

function pyb_loadConfirmedHistory_(ss, tz, weekStartStr) {
  var sheet = ss.getSheetByName('確定スケジュール履歴');
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length < 2) return [];
  var h = data[0];

  function fc(name) {
    for (var i = 0; i < h.length; i++) {
      if (String(h[i]).indexOf(name) >= 0) return i;
    }
    return -1;
  }

  var ci = { ws: fc('週開始日'), date: fc('日付'), pid: fc('patient_id'), sid: fc('staff_id'), sname: fc('スタッフ名') };

  // Only load records BEFORE this week
  var results = [];
  for (var i = 1; i < data.length; i++) {
    var r = data[i];
    var ws = ci.ws >= 0 ? String(r[ci.ws] || '') : '';
    if (ws >= weekStartStr) continue; // Only BEFORE this week

    var dateVal = ci.date >= 0 ? r[ci.date] : null;
    var dateStr = dateVal ? ((dateVal instanceof Date) ? Utilities.formatDate(dateVal, tz, 'yyyy/MM/dd') : String(dateVal)) : '';

    results.push({
      week_start: ws,
      date: dateStr,
      patient_id: ci.pid >= 0 ? String(r[ci.pid] || '') : '',
      staff_id: ci.sid >= 0 ? String(r[ci.sid] || '') : '',
      staff_name: ci.sname >= 0 ? String(r[ci.sname] || '') : ''
    });
  }
  return results;
}

// ============================================================
// NEW: Patient Changes Loader (個別変更リクエスト)
// ============================================================

function pyb_loadPatientChanges_(ss, tz, weekStartStr) {
  var sheet = ss.getSheetByName('個別変更リクエスト');
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length < 2) return [];
  var h = data[0];

  function fc(name) {
    for (var i = 0; i < h.length; i++) {
      var hv = String(h[i]).replace(/[\s\u3000]/g, '');
      if (hv.indexOf(name.replace(/[\s\u3000]/g, '')) >= 0) return i;
    }
    return -1;
  }

  var ci = {
    pid: fc('patient_id'), date: fc('日付'), op: fc('操作'),
    timeType: fc('時間タイプ'),
    newStart: fc('開始時刻'), newEnd: fc('終了時刻'),
    earliest: fc('希望最早'), latest: fc('希望最遅'),
    svc: fc('サービス時間'), need: fc('必要スタッフ数'),
    specIds: fc('指定スタッフID'), specType: fc('指定タイプ'),
    ngIds: fc('NGスタッフID'), note: fc('備考')
  };
  // 「開始時刻(固定)」列があればそちらを優先
  var fixedStart = fc('開始時刻(固定)');
  var fixedEnd = fc('終了時刻(固定)');
  if (fixedStart >= 0) ci.newStart = fixedStart;
  if (fixedEnd >= 0) ci.newEnd = fixedEnd;

  // Week date range
  var wsParts = weekStartStr.split('/');
  var wsDate = new Date(parseInt(wsParts[0]), parseInt(wsParts[1]) - 1, parseInt(wsParts[2]));
  var weekDates = {};
  for (var d = 0; d < 7; d++) {
    var dd = new Date(wsDate.getTime() + d * 86400000);
    weekDates[Utilities.formatDate(dd, tz, 'yyyy/MM/dd')] = true;
  }

  var results = [];
  for (var i = 1; i < data.length; i++) {
    var r = data[i];
    var dateVal = ci.date >= 0 ? r[ci.date] : null;
    if (!dateVal) continue;
    var dateStr = (dateVal instanceof Date) ? Utilities.formatDate(dateVal, tz, 'yyyy/MM/dd') : String(dateVal);
    if (!weekDates[dateStr]) continue;

    var op = ci.op >= 0 ? String(r[ci.op] || '').trim() : '';
    if (!op) continue;

    results.push({
      patient_id: ci.pid >= 0 ? String(r[ci.pid] || '') : '',
      date: dateStr,
      operation: op,
      time_type: ci.timeType >= 0 ? String(r[ci.timeType] || '') : '',
      start_time_minutes: ci.newStart >= 0 ? pyb_timeToMin_(r[ci.newStart], tz) : null,
      end_time_minutes: ci.newEnd >= 0 ? pyb_timeToMin_(r[ci.newEnd], tz) : null,
      earliest_time_minutes: ci.earliest >= 0 ? pyb_timeToMin_(r[ci.earliest], tz) : null,
      latest_time_minutes: ci.latest >= 0 ? pyb_timeToMin_(r[ci.latest], tz) : null,
      service_minutes: ci.svc >= 0 ? (Number(r[ci.svc]) || null) : null,
      need_staff: ci.need >= 0 ? (Number(r[ci.need]) || null) : null,
      specified_staff_ids: ci.specIds >= 0 ? pyb_parseList_(r[ci.specIds]) : [],
      specified_type: ci.specType >= 0 ? String(r[ci.specType] || '') : '',
      ng_staff_ids: ci.ngIds >= 0 ? pyb_parseList_(r[ci.ngIds]) : [],
      note: ci.note >= 0 ? String(r[ci.note] || '') : ''
    });
  }
  return results;
}

// ============================================================
// NEW: Special Week Loader (特別訪問週間)
// ============================================================

function pyb_loadSpecialWeek_(ss, tz, weekStartStr) {
  var shH = ss.getSheetByName('特別訪問週間_ヘッダ');
  var shD = ss.getSheetByName('特別訪問週間_明細');
  if (!shH || !shD) return { headers: [], details: [] };

  var hValues = shH.getDataRange().getValues();
  var dValues = shD.getDataRange().getValues();
  if (hValues.length <= 1) return { headers: [], details: [] };

  var hHeader = hValues[0];
  var hData = hValues.slice(1);
  var dHeader = dValues.length ? dValues[0] : [];
  var dData = dValues.length > 1 ? dValues.slice(1) : [];

  var idxH = {};
  hHeader.forEach(function(k, i) { idxH[k] = i; });
  var idxD = {};
  dHeader.forEach(function(k, i) { idxD[k] = i; });

  // Column name compatibility
  var hIdCol = idxH['special_week_id'] != null ? 'special_week_id' : 'special_id';
  var dIdCol = idxD['special_week_id'] != null ? 'special_week_id' : 'special_id';
  var hModeCol = idxH['適用モード(ADD/REPLACE)'] != null ? '適用モード(ADD/REPLACE)' : 'モード';
  var dTimeTypeCol = idxD['時間タイプ'] != null ? '時間タイプ' : 'timeType';
  var dEarliestCol = idxD['希望最早'] != null ? '希望最早' : '希望最早時刻';
  var dLatestCol = idxD['希望最遅'] != null ? '希望最遅' : '希望最遅時刻';

  // Filter headers for this week
  var headers = [];
  hData.forEach(function(r) {
    var id = r[idxH[hIdCol]];
    if (!id) return;

    var ws = r[idxH['週開始日']];
    var wsObj = (ws instanceof Date) ? ws : pyb_parseDate_(ws);
    if (!wsObj) return;
    var wsStr = Utilities.formatDate(wsObj, tz, 'yyyy/MM/dd');
    if (wsStr !== weekStartStr) return;

    var status = idxH['状態'] != null ? String(r[idxH['状態']] || '').trim() : '有効';
    if (status && status !== '有効') return;

    var modeRaw = r[idxH[hModeCol]] || '';
    var mode = String(modeRaw).trim().toUpperCase();
    if (mode === '追加' || mode === 'ADD') mode = 'ADD';
    else if (mode === '置換' || mode === 'REPLACE') mode = 'REPLACE';
    else mode = 'ADD';

    headers.push({
      special_week_id: String(id),
      patient_id: String(r[idxH['patient_id']] || ''),
      patient_name: idxH['患者名'] != null ? String(r[idxH['患者名']] || '') : '',
      week_start: wsStr,
      mode: mode,
      reason: idxH['理由'] != null ? String(r[idxH['理由']] || '') : ''
    });
  });

  if (headers.length === 0) return { headers: [], details: [] };

  var idSet = {};
  headers.forEach(function(h) { idSet[h.special_week_id] = true; });

  // Parse week date range for filtering details
  var wsParts = weekStartStr.split('/');
  var wsDate = new Date(parseInt(wsParts[0]), parseInt(wsParts[1]) - 1, parseInt(wsParts[2]));
  var weDate = new Date(wsDate.getTime() + 6 * 86400000);

  var details = [];
  dData.forEach(function(r) {
    var id = String(r[idxD[dIdCol]] || '');
    if (!id || !idSet[id]) return;

    var dateVal = r[idxD['日付']];
    var dateObj = (dateVal instanceof Date) ? dateVal : pyb_parseDate_(dateVal);
    if (!dateObj || dateObj < wsDate || dateObj > weDate) return;

    var dateStr = Utilities.formatDate(dateObj, tz, 'yyyy/MM/dd');

    details.push({
      special_week_id: id,
      patient_id: String(r[idxD['patient_id']] || ''),
      date: dateStr,
      time_type: idxD[dTimeTypeCol] != null ? String(r[idxD[dTimeTypeCol]] || '') : '',
      start_time_minutes: idxD['開始時刻'] != null ? pyb_timeToMin_(r[idxD['開始時刻']], tz) : null,
      end_time_minutes: idxD['終了時刻'] != null ? pyb_timeToMin_(r[idxD['終了時刻']], tz) : null,
      earliest_time_minutes: idxD[dEarliestCol] != null ? pyb_timeToMin_(r[idxD[dEarliestCol]], tz) : null,
      latest_time_minutes: idxD[dLatestCol] != null ? pyb_timeToMin_(r[idxD[dLatestCol]], tz) : null,
      service_minutes: idxD['サービス時間'] != null ? (Number(r[idxD['サービス時間']]) || 60) : 60,
      need_staff: idxD['必要スタッフ数'] != null ? (Number(r[idxD['必要スタッフ数']]) || 1) : 1,
      note: idxD['備考'] != null ? String(r[idxD['備考']] || '') : '',
      change_policy: idxD['個別変更の扱い'] != null ? String(r[idxD['個別変更の扱い']] || '') : ''
    });
  });

  return { headers: headers, details: details };
}

// ============================================================
// NEW: Mentor Pairs Loader (スタッフ同行割付)
// ============================================================

function pyb_loadMentorPairs_(ss, tz, weekStartStr) {
  var sheet = ss.getSheetByName('スタッフ同行割付');
  if (!sheet) return [];
  var data = sheet.getDataRange().getValues();
  if (data.length < 2) return [];
  var h = data[0];

  function fc(name) {
    for (var i = 0; i < h.length; i++) {
      if (String(h[i]).indexOf(name) >= 0) return i;
    }
    return -1;
  }

  var ci = {
    trainee: fc('trainee_staff_id'), mentor: fc('mentor_staff_id'),
    startDate: fc('開始日'), endDate: fc('終了日'),
    band: fc('時間帯'), startTime: fc('開始時刻'), endTime: fc('終了時刻'),
    dayCondition: fc('曜日条件'), priority: fc('優先度')
  };

  // Week date range
  var wsParts = weekStartStr.split('/');
  var wsDate = new Date(parseInt(wsParts[0]), parseInt(wsParts[1]) - 1, parseInt(wsParts[2]));
  var weDate = new Date(wsDate.getTime() + 6 * 86400000);

  var results = [];
  for (var i = 1; i < data.length; i++) {
    var r = data[i];
    var traineeId = ci.trainee >= 0 ? String(r[ci.trainee] || '') : '';
    if (!traineeId) continue;

    // Check date range overlap with this week
    var sd = ci.startDate >= 0 ? r[ci.startDate] : null;
    var ed = ci.endDate >= 0 ? r[ci.endDate] : null;
    var sdObj = sd ? ((sd instanceof Date) ? sd : pyb_parseDate_(sd)) : null;
    var edObj = ed ? ((ed instanceof Date) ? ed : pyb_parseDate_(ed)) : null;

    // Skip if pair date range does not overlap with this week
    if (sdObj && sdObj > weDate) continue;
    if (edObj && edObj < wsDate) continue;

    results.push({
      trainee_staff_id: traineeId,
      mentor_staff_id: ci.mentor >= 0 ? String(r[ci.mentor] || '') : '',
      start_date: sdObj ? Utilities.formatDate(sdObj, tz, 'yyyy/MM/dd') : '',
      end_date: edObj ? Utilities.formatDate(edObj, tz, 'yyyy/MM/dd') : '',
      band: ci.band >= 0 ? String(r[ci.band] || '') : '',
      start_time_minutes: ci.startTime >= 0 ? pyb_timeToMin_(r[ci.startTime], tz) : null,
      end_time_minutes: ci.endTime >= 0 ? pyb_timeToMin_(r[ci.endTime], tz) : null,
      day_condition: ci.dayCondition >= 0 ? String(r[ci.dayCondition] || '') : '',
      priority: ci.priority >= 0 ? String(r[ci.priority] || '') : ''
    });
  }
  return results;
}

// ============================================================
// Write Results Functions (Private)
// ============================================================

function pyb_writeAssignmentResults_(ss, tz, assignments) {
  var sheet = ss.getSheetByName('割当結果');
  if (!sheet) {
    sheet = ss.insertSheet('割当結果');
  }

  // Clear and write header
  sheet.clear();
  var headers = ['visit_id', '日付', '曜日', 'staff_id', 'スタッフ名', 'patient_id', '患者名', 'エリア', '開始時刻', '終了時刻', 'サービス時間', '時間タイプ', '希望最早時刻', '希望最遅時刻', '移動距離(km)', '移動時間(分)', '備考'];
  sheet.getRange(1, 1, 1, headers.length).setValues([headers]);

  if (assignments.length === 0) return;

  var rows = [];
  for (var i = 0; i < assignments.length; i++) {
    var a = assignments[i];
    var dateVal = a.date ? pyb_parseDate_(a.date) : '';
    rows.push([
      a.visit_id || '',
      dateVal || a.date || '',
      a.weekday || '',
      a.staff_id || '',
      a.staff_name || '',
      a.patient_id || '',
      a.patient_name || '',
      a.area || '',
      a.start_time_minutes != null ? a.start_time_minutes / 1440 : '',
      a.end_time_minutes != null ? a.end_time_minutes / 1440 : '',
      a.service_minutes || '',
      a.time_type || '',
      a.earliest_time_minutes != null ? a.earliest_time_minutes / 1440 : '',
      a.latest_time_minutes != null ? a.latest_time_minutes / 1440 : '',
      a.movement_km != null ? a.movement_km : '',
      a.movement_km != null ? Math.round(a.movement_km / 30 * 60) : '',
      a.notes || ''
    ]);
  }

  sheet.getRange(2, 1, rows.length, headers.length).setValues(rows);
}

function pyb_writeUnassigned_(ss, tz, unassigned) {
  var sheet = ss.getSheetByName('割当不可');
  if (!sheet) {
    sheet = ss.insertSheet('割当不可');
  }
  sheet.clear();
  var headers = ['日付', '曜日', 'patient_id', '患者名', '必要スタッフ数', '未割当枠', '理由'];
  sheet.getRange(1, 1, 1, headers.length).setValues([headers]);

  if (unassigned.length === 0) return;

  var rows = [];
  for (var i = 0; i < unassigned.length; i++) {
    var u = unassigned[i];
    rows.push([
      u.date_str || u.date || '',
      '',
      u.pid || u.patient_id || '',
      u.pname || u.patient_name || '',
      u.need_staff || 1,
      u.slot || 1,
      u.reason || ''
    ]);
  }
  sheet.getRange(2, 1, rows.length, headers.length).setValues(rows);
}

// ============================================================
// Utility Functions (Private)
// ============================================================

function pyb_timeToMin_(val, tz) {
  if (val === null || val === undefined || val === '') return null;
  if (val instanceof Date) {
    return val.getHours() * 60 + val.getMinutes();
  }
  if (typeof val === 'number') {
    if (val >= 0 && val < 1) return Math.round(val * 24 * 60);
    if (val >= 1 && val < 1440) return Math.round(val);
    return Math.round(val * 24 * 60) % 1440;
  }
  var s = String(val).trim();
  var m = s.match(/(\d{1,2}):(\d{2})/);
  if (m) return parseInt(m[1]) * 60 + parseInt(m[2]);
  return null;
}

function pyb_parseDate_(dateStr) {
  if (!dateStr) return null;
  var parts = String(dateStr).split(/[\/\-]/);
  if (parts.length >= 3) {
    return new Date(parseInt(parts[0]), parseInt(parts[1]) - 1, parseInt(parts[2]));
  }
  return null;
}

function pyb_parseList_(val) {
  if (!val) return [];
  return String(val).split(/[,、\s\/・|]+/).map(function(s) { return s.trim(); }).filter(function(s) { return s; });
}

function pyb_parseDayList_(val) {
  if (!val) return [];
  var items = pyb_parseList_(val);
  var dayMap = {'月':'Mon','火':'Tue','水':'Wed','木':'Thu','金':'Fri','土':'Sat','日':'Sun'};
  return items.map(function(d) { return dayMap[d] || d; });
}

function pyb_normalizeWeekday_(val) {
  if (!val) return '';
  var s = String(val).trim();
  var dayMap = {'月':'Mon','火':'Tue','水':'Wed','木':'Thu','金':'Fri','土':'Sat','日':'Sun',
    'Mon':'Mon','Tue':'Tue','Wed':'Wed','Thu':'Thu','Fri':'Fri','Sat':'Sat','Sun':'Sun'};
  return dayMap[s] || s;
}
